### ISSUE TITLE
little suggestion

### ISSUE THREAD

**Issue by glepnir** [zhaozg/neospace#2]
```lua    
map(bufnr, "n", "cd", "<cmd>Lspsaga preview_definition<CR>")
 map(bufnr, "v", "ga", "<cmd><C-U>Lspsaga range_code_action<CR>")
map(bufnr, "n", "ch", "<cmd>Lspsaga signature_help<CR>")
```

这三个我已经removed 好久了。用的是fork的version吗

```
options.repo_base = "https://github.com/"
```
插件支持local 或者gitlab 等等更好。

结构感觉怪怪的。其实可以自己设计一套呀 。

terminal + neovim =  yyds 👍

**Comment by zhaozg** [comment]
你好, 我这是用到后发现问题才去修改, keymap 这块乱的很, 勉强够自己用.  时间上不能及时更新各plugin配置以适应最新的版本.

感谢你的大作哦. Lspsaga 挺棒的.

**Comment by zhaozg** [comment]
该配置大部分都是用github的上源仓库, 尽量不用fork的.

**Comment by glepnir** [comment]
vim.keymap.set 这个就是个语法糖，基于这个的话不太好封装，或者你可以基于api在封装一套，配置这东西自己舒服最好，简单就好其实
